
(() => {
const CFG=window.LOG4TELLS_CONFIG||{}, demo=[
{id:"demo-1",author_id:"demo",name:"Maya Chen",username:"mayac",body:"The interesting thing about social feeds is that the ranking is part of the product. I want to know what the feed thinks matters to me.",topic:"Social systems",created_at:new Date(Date.now()-12*60000).toISOString(),likes:184,following:true},
{id:"demo-2",author_id:"demo2",name:"Arif Rahman",username:"arif",body:"A good feed should let me choose between familiar people, new ideas, and chronological updates without hunting through settings.",topic:"Product design",created_at:new Date(Date.now()-31*60000).toISOString(),likes:96,following:false},
{id:"demo-3",author_id:"demo3",name:"Nora Singh",username:"nora",body:"I saved a post six months ago and could not remember why. Social memory needs context, not just a bookmark.",topic:"Digital memory",created_at:new Date(Date.now()-60*60000).toISOString(),likes:221,following:true},
{id:"demo-4",author_id:"demo4",name:"Jon Bell",username:"jonbell",body:"Popularity tells you what is moving. It does not necessarily tell you what is useful. Those should be separate signals.",topic:"Ranking",created_at:new Date(Date.now()-95*60000).toISOString(),likes:73,following:false}
];
const modes=[["relationship","People"],["balanced","Balanced"],["discovery","Discover"],["chronological","Latest"]];
const defaults={mode:"balanced",relationship_weight:30,interest_weight:25,freshness_weight:20,novelty_weight:10,diversity_weight:15};
let sb=null,user=null,profile=null,prefs={...defaults},posts=[],saved=new Set(),reactions=new Set(),hidden=new Set(),expanded=null;
const app=document.querySelector("#app");
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const initials=n=>String(n||"L").split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
const ago=iso=>{const m=Math.max(1,Math.floor((Date.now()-new Date(iso))/60000));return m<60?m+"m":m<1440?Math.floor(m/60)+"h":Math.floor(m/1440)+"d"};
const toast=m=>{const d=document.createElement("div");d.className="toast";d.textContent=m;document.body.appendChild(d);setTimeout(()=>d.remove(),3000)};
const live=()=>!!sb;
function initClient(){if(CFG.supabaseUrl&&CFG.supabasePublishableKey&&window.supabase)sb=window.supabase.createClient(CFG.supabaseUrl,CFG.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
async function start(){
 initClient();
 if(sb){const {data}=await sb.auth.getSession();user=data.session?.user||null;sb.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;await hydrate();render()});await hydrate()}
 render();
}
async function hydrate(){
 if(!sb){profile=null;posts=[];return}
 if(!user){profile=null;posts=[];return}
 const pr=await sb.from("profiles").select("*").eq("id",user.id).maybeSingle();profile=pr.data||null;
 if(profile){
  const fp=await sb.from("feed_preferences").select("*").eq("user_id",user.id).maybeSingle();if(fp.data)prefs={...defaults,...fp.data};
  const sv=await sb.from("saves").select("post_id").eq("user_id",user.id);saved=new Set((sv.data||[]).map(x=>x.post_id));
  const rx=await sb.from("reactions").select("post_id").eq("user_id",user.id);reactions=new Set((rx.data||[]).map(x=>x.post_id));
  await loadPosts();
 }
}
async function loadPosts(){
 const r=await sb.from("posts").select("id,author_id,body,topic,visibility,created_at,profiles:author_id(id,display_name,username,avatar_url)").order("created_at",{ascending:false}).limit(80);
 if(r.error){toast(r.error.message);return}
 const rows=r.data||[],ids=rows.map(x=>x.id);let counts={},following=new Set();
 if(ids.length){const rr=await sb.from("reactions").select("post_id").in("post_id",ids);(rr.data||[]).forEach(x=>counts[x.post_id]=(counts[x.post_id]||0)+1);const ff=await sb.from("follows").select("followed_id").eq("follower_id",user.id);following=new Set((ff.data||[]).map(x=>x.followed_id))}
 posts=rows.map(x=>({...x,name:x.profiles?.display_name||"Member",username:x.profiles?.username||"member",likes:counts[x.id]||0,following:following.has(x.author_id)}));
}
function ranked(list){
 const mode=prefs.mode||"balanced",now=Date.now();
 return list.filter(p=>!hidden.has(p.id)).map((p,i)=>{
  const age=Math.max(1,(now-new Date(p.created_at))/3600000),fresh=1/(1+age/12),rel=p.following?1:0,novel=p.author_id===user?.id?0:.7,div=i%3===1?.95:.62;
  let score=mode==="chronological"?-new Date(p.created_at).getTime():mode==="relationship"?rel*100+fresh*10:mode==="discovery"?novel*55+div*35+fresh*10:rel*prefs.relationship_weight+fresh*prefs.freshness_weight+novel*prefs.novelty_weight+div*prefs.diversity_weight;
  const reasons=[];if(rel)reasons.push("You follow this person");if(fresh>.55)reasons.push("Fresh in your feed");if(mode==="discovery"&&!rel)reasons.push("Adds a new perspective");if(mode==="balanced")reasons.push("Fits your balanced recipe");if(div>.8)reasons.push("Adds variety");
  return {...p,_score:score,_reasons:reasons};
 }).sort((a,b)=>b._score-a._score);
}
function avatar(p){return `<div class="avatar">${esc(initials(p?.display_name||p?.name))}</div>`}
function composer(){return user&&profile?`<section class="composer"><textarea id="composerText" maxlength="5000" placeholder="What are you noticing, thinking, expecting, or learning?"></textarea><div class="composer-row"><input class="topic" id="composerTopic" maxlength="60" placeholder="Topic (optional)"><button class="btn dark" data-action="publish">Publish tell</button></div></section>`:""}
function sidebar(){return `<div class="panel"><h3>YOUR RANKING</h3><p>Explicit preferences come before inferred behavior.</p>${["relationship_weight","interest_weight","freshness_weight","novelty_weight","diversity_weight"].map(k=>`<div class="recipe-row"><div class="recipe-label"><span>${k.replace("_weight","")}</span><b>${prefs[k]}%</b></div><input class="range" type="range" min="0" max="60" step="5" value="${prefs[k]}" data-pref="${k}"></div>`).join("")}<button class="btn" data-action="saveprefs" style="width:100%;margin-top:6px">${user?"Save my recipe":"Sign in to save recipe"}</button></div><div class="panel"><h3>WHY THIS EXISTS</h3><p>A social feed is not neutral. Ordering is a product decision. Log4tells makes that decision visible and adjustable.</p><div class="statline"><span>Mode</span><b>${esc(prefs.mode)}</b></div><div class="statline"><span>Ranking</span><b>v1-transparent</b></div></div><div class="panel"><h3>PRINCIPLES</h3><p>Relationship is not popularity. Popularity is not quality. Freshness is not truth. Discovery does not require outrage.</p></div>`}
function card(p){
 const why=expanded===p.id,liked=reactions.has(p.id),sv=saved.has(p.id);
 return `<article class="card"><div class="post-head">${avatar(p)}<div><div class="author">${esc(p.name)}</div><div class="meta">@${esc(p.username)} · ${ago(p.created_at)} ${p.topic?`· ${esc(p.topic)}`:""}</div></div><div class="spacer"></div>${user&&p.author_id!==user.id?`<button class="btn tiny" data-follow="${p.author_id}" data-following="${p.following}">${p.following?"Following":"Follow"}</button>`:""}<button class="btn tiny" data-hide="${p.id}">•••</button></div><div class="body">${esc(p.body)}</div>${p.topic?`<span class="topic-label">${esc(p.topic)}</span>`:""}${why?`<div class="why"><strong>WHY YOU'RE SEEING THIS</strong><div>${p._reasons.map(r=>`<span class="reason">${esc(r)}</span>`).join("")}</div><p>Ranking version <b>v1-transparent</b>. Your selected mode and recipe shape this order. Reaction count is not the sole ranking signal.</p></div>`:""}<div class="post-actions"><button class="action ${why?"active":""}" data-why="${p.id}">${why?"Hide why":"Why this?"}</button>${user?`<button class="action ${liked?"active":""}" data-like="${p.id}">${liked?"♥ Reacted":"♡ React"} ${p.likes||""}</button><button class="action ${sv?"active":""}" data-save="${p.id}">${sv?"✓ Saved":"＋ Save context"}</button>`:`<span class="action">${p.likes||0} reactions</span>`}<button class="action" data-not="${p.id}">Not interested</button></div></article>`
}
function feed(){const list=ranked(live()&&user?posts:demo);return list.length?list.map(card).join(""):`<div class="empty"><strong>Your feed is quiet.</strong><span>Publish a tell or follow someone to give it shape.</span></div>`}
function modal(kind="auth"){if(kind==="recipe")return `<div class="modal-backdrop" id="modal"><div class="modal"><h2>Make the feed yours.</h2><p>Adjust the ranking recipe. It becomes persistent when saved to Supabase.</p>${["relationship_weight","interest_weight","freshness_weight","novelty_weight","diversity_weight"].map(k=>`<div class="recipe-row"><div class="recipe-label"><span>${k.replace("_weight","")}</span><b id="mv-${k}">${prefs[k]}%</b></div><input class="range" type="range" min="0" max="60" step="5" value="${prefs[k]}" data-modal-pref="${k}"></div>`).join("")}<div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn dark" data-action="saveprefs">Save recipe</button></div></div></div>`;
 return `<div class="modal-backdrop" id="modal"><div class="modal"><h2>Welcome to Log4tells</h2><p>Create an account to publish, follow people, save context and make the ranking yours.</p><input class="field" id="authEmail" type="email" placeholder="Email"><input class="field" id="authPassword" type="password" placeholder="Password (6+ characters)"><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn" data-action="signin">Sign in</button><button class="btn dark" data-action="signup">Create account</button></div></div></div>`}
function page(){return `<div class="shell"><header class="topbar"><a class="brand" href="/"><span class="logo">L4</span><span><strong>LOG4TELLS</strong><small>Your social world. Your ranking.</small></span></a><div class="top-actions">${user?`<span class="desktop-only" style="font-size:11px;color:var(--muted)">${esc(profile?.display_name||"Account")}</span><button class="btn ghost" data-action="signout">Sign out</button>`:`<button class="btn ghost" data-action="auth">Sign in</button>`}<button class="btn dark" data-action="compose">Tell something</button></div></header><div class="layout"><main class="main"><section class="hero"><div class="eyebrow">LOG4TELLS · FEED CONTRACT</div><h1>See your social world.<br>Choose how it is ranked.</h1><p>Familiar people, fresh ideas and discovery can coexist — and every card can explain why it is here.</p><div class="contract"><span class="pill">User-controlled</span><span class="pill">Why this?</span><span class="pill">Popularity ≠ quality</span><span class="pill">No engagement-only ranking</span></div></section>${!live()?`<div class="notice">Demo mode is active. Configure Supabase in <b>supabase-config.js</b> to make accounts and interactions persistent.</div>`:user&&!profile?`<div class="notice">Account created. Finish your profile to start publishing.</div>`:""}${user&&profile?composer():user?"":`<div class="composer"><b>Join the feed</b><p style="font-size:12px;color:var(--muted)">Sign in to publish, follow people, save context and shape your own feed.</p><button class="btn dark" data-action="auth">Create account / Sign in</button></div>`}<div class="controls"><div class="modes">${modes.map(m=>`<button class="mode ${prefs.mode===m[0]?"active":""}" data-mode="${m[0]}">${m[1]}</button>`).join("")}</div><button class="btn tiny" data-action="recipe">Tune feed</button></div>${feed()}<div class="footer">Log4tells · V1 transparent feed experiment · log4tells.com</div></main><aside class="sidebar">${sidebar()}</aside></div><nav class="mobile-nav"><button class="active" data-action="top">FEED</button><button data-action="recipe">TUNE</button><button data-action="compose">TELL</button><button data-action="auth">${user?"ACCOUNT":"JOIN"}</button></nav></div>`}
function render(){app.innerHTML=page()}
async function auth(type){if(!sb){toast("Connect Supabase first in supabase-config.js.");return}const email=document.querySelector("#authEmail").value.trim(),password=document.querySelector("#authPassword").value,r=type==="signup"?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});if(r.error){toast(r.error.message);return}document.querySelector("#modal")?.remove();if(type==="signup"&&!r.data.session)toast("Account created. Check your email, then sign in.");else{user=r.data.user;await hydrate();render();if(!profile)toast("Now finish your profile in the next step.")}}
async function createProfile(){const name=prompt("Display name")?.trim(),username=prompt("Username (letters, numbers, underscore)")?.trim().toLowerCase();if(!name||!username)return;const r=await sb.from("profiles").insert({id:user.id,display_name:name,username});if(r.error){toast(r.error.message);return}await sb.from("feed_preferences").upsert({user_id:user.id,...defaults});await hydrate();render();toast("Profile ready.")}
async function publish(){const body=document.querySelector("#composerText")?.value.trim(),topic=document.querySelector("#composerTopic")?.value.trim();if(!body)return toast("Write something first.");const r=await sb.from("posts").insert({author_id:user.id,body,topic:topic||null,visibility:"public"});if(r.error){toast(r.error.message);return}await loadPosts();render();toast("Published.")}
async function savePrefs(){if(!user){toast("Sign in to save your recipe.");return}const r=await sb.from("feed_preferences").upsert({user_id:user.id,mode:prefs.mode,relationship_weight:prefs.relationship_weight,interest_weight:prefs.interest_weight,freshness_weight:prefs.freshness_weight,novelty_weight:prefs.novelty_weight,diversity_weight:prefs.diversity_weight});if(r.error)toast(r.error.message);else{document.querySelector("#modal")?.remove();toast("Feed recipe saved.");render()}}
async function follow(id,isFollowing){const r=isFollowing?await sb.from("follows").delete().eq("follower_id",user.id).eq("followed_id",id):await sb.from("follows").insert({follower_id:user.id,followed_id:id});if(r.error)toast(r.error.message);else{await loadPosts();render()}}
async function react(id){const r=reactions.has(id)?await sb.from("reactions").delete().eq("user_id",user.id).eq("post_id",id):await sb.from("reactions").insert({user_id:user.id,post_id:id,kind:"like"});if(r.error)toast(r.error.message);else{await hydrate();render()}}
async function save(id){const r=saved.has(id)?await sb.from("saves").delete().eq("user_id",user.id).eq("post_id",id):await sb.from("saves").insert({user_id:user.id,post_id:id});if(r.error)toast(r.error.message);else{await hydrate();render()}}
async function feedback(id){const r=await sb.from("feed_feedback").insert({user_id:user.id,post_id:id,feedback:"not_interested"});if(r.error)toast(r.error.message);else{hidden.add(id);render();toast("Your feed will use that signal.")}}
app.addEventListener("click",async e=>{const t=e.target.closest("[data-action],[data-mode],[data-why],[data-save],[data-like],[data-follow],[data-hide],[data-not],[data-close]");if(!t)return;if(t.dataset.close){document.querySelector("#modal")?.remove();return}if(t.dataset.mode){prefs.mode=t.dataset.mode;render();return}if(t.dataset.why){expanded=expanded===t.dataset.why?null:t.dataset.why;render();return}if(t.dataset.follow){if(!user)return document.body.insertAdjacentHTML("beforeend",modal());await follow(t.dataset.follow,t.dataset.following==="true");return}if(t.dataset.like){if(!user)return document.body.insertAdjacentHTML("beforeend",modal());await react(t.dataset.like);return}if(t.dataset.save){if(!user)return document.body.insertAdjacentHTML("beforeend",modal());await save(t.dataset.save);return}if(t.dataset.not){if(!user)return document.body.insertAdjacentHTML("beforeend",modal());await feedback(t.dataset.not);return}if(t.dataset.hide){hidden.add(t.dataset.hide);render();return}const a=t.dataset.action;if(a==="auth")document.body.insertAdjacentHTML("beforeend",modal());else if(a==="signin")await auth("signin");else if(a==="signup")await auth("signup");else if(a==="signout"){await sb.auth.signOut();toast("Signed out.")}else if(a==="compose"){if(!user)return document.body.insertAdjacentHTML("beforeend",modal());if(!profile)return createProfile();document.querySelector("#composerText")?.focus();window.scrollTo({top:0,behavior:"smooth"})}else if(a==="publish")await publish();else if(a==="recipe")document.body.insertAdjacentHTML("beforeend",modal("recipe"));else if(a==="saveprefs")await savePrefs();else if(a==="top")window.scrollTo({top:0,behavior:"smooth"})});
app.addEventListener("input",e=>{const k=e.target.dataset.pref||e.target.dataset.modalPref;if(!k)return;prefs[k]=Number(e.target.value);const o=document.querySelector("#mv-"+k);if(o)o.textContent=prefs[k]+"%"});
start();
})();
